<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DEFAULT_LABEL' => 'Yangi rasmni yuklash uchun shu yerga bosing',
    'CROP_PHOTO' => 'Rasmni qirqish',
    'CANCEL' => 'Bekor qilish',
    'PREVIEW' => 'Oldindan ko\'rish',
    'ERROR_NO_SAVE_DIR' => 'Saqlash papkasi yaratilmagan',
    'DESCRIPTION' => 'Zarur maydonni belgilang va rasmni qirqish tugmasiga bosing',
    'ERROR_CAN_NOT_UPLOAD_FILE' => 'Faylni yuklab bo\'lmadi',
    'MISSING_ATTRIBUTE' => '"{attribute}" atributi ko\'rsatilgan bo\'lishi lozim',
    'ONLY_POST_REQUEST' => 'Faqat POST-so\rovlarga ruxsat etilgan',
    'TOO_BIG_ERROR' => 'Belgilangan o\'lchamdan ({size} Mb) katta fayllarni yuklashga ruxsat etilmaydi',
    'EXTENSION_ERROR' => 'Faqat quyidagi kengaytmadagi fayllarni yuklashga ruxsat etiladi: {formats}'
];
